Bluetooth: btrsi: rework dependencies
BugLink: https://bugs.launchpad.net/bugs/1782070

The linkage between the bluetooth driver and the wireless
driver is not defined properly, leading to build problems
such as:

warning: (BT_HCIRSI) selects RSI_COEX which has unmet direct dependencies
(NETDEVICES && WLAN && WLAN_VENDOR_RSI && BT_HCIRSI && RSI_91X)
drivers/net/wireless/rsi/rsi_91x_main.o: In function `rsi_read_pkt':
(.text+0x205): undefined reference to `rsi_bt_ops'

As the dependency is actually the reverse (RSI_91X uses
the BT_RSI driver, not the other way round), this changes
the dependency to match, and enables the bluetooth driver
from the RSI_COEX symbol.

Fixes: 38aa4da50483 ("Bluetooth: btrsi: add new rsi bluetooth driver")
Acked-by; Marcel Holtmann <marcel at holtmann.org>
Signed-off-by: Arnd Bergmann <arnd at arndb.de>
Signed-off-by: Kalle Valo <kvalo at codeaurora.org>
(cherry picked from commit 255dd5b79d5474dad3ecebe99be7818684921abd)
Signed-off-by: Shrirang Bagul <shrirang.bagul at canonical.com>
Acked-by: Anthony Wong <anthony.wong@canonical.com>
Acked-by: Chia-Lin Kao (AceLan) <acelan.kao@canonical.com>